// Statyczna hierarchia jednostek administracyjnych Polski (TERYT)
// Klucze powiatów: bez prefiksu "powiat" (np. "wrocławski")
// Miasta na prawach powiatu: pełna nazwa miasta (np. "Wrocław")
const TERYT: Record<string, Record<string, string[]>> = {
  dolnoslaskie: {
    bolesławiecki: ["Bolesławiec", "Gromadka", "Nowogrodziec", "Osiecznica", "Warta Bolesławiecka"],
    dzierżoniowski: ["Bielawa", "Dzierżoniów", "Łagiewniki", "Niemcza", "Pieszyce", "Piława Górna"],
    głogowski: ["Głogów", "Jerzmanowa", "Pęcław", "Żukowice"],
    górowski: ["Góra", "Jemielno", "Niechlów", "Wąsosz"],
    jaworski: ["Bolków", "Jawor", "Mściwojów", "Paszowice", "Wądroże Wielkie"],
    jeleniogórski: ["Janowice Wielkie", "Jeżów Sudecki", "Mysłakowice", "Podgórzyn", "Stara Kamienica", "Szklarska Poręba"],
    kamiennogórski: ["Kamienna Góra", "Lubawka", "Marciszów"],
    kłodzki: ["Bystrzyca Kłodzka", "Duszniki-Zdrój", "Kłodzko", "Kudowa-Zdrój", "Lądek-Zdrój", "Lewin Kłodzki", "Międzylesie", "Nowa Ruda", "Radków", "Stronie Śląskie", "Szczytna"],
    legnicki: ["Chojnów", "Krotoszyce", "Kunice", "Legnickie Pole", "Miłkowice", "Prochowice", "Ruja"],
    lubański: ["Leśna", "Lubań", "Olszyna", "Platerówka", "Siekierczyn"],
    lubiński: ["Lubin", "Rudna", "Ścinawa"],
    lwówecki: ["Gryfów Śląski", "Lwówek Śląski", "Mirsk", "Wleń"],
    milicki: ["Cieszków", "Krośnice", "Milicz"],
    oleśnicki: ["Bierutów", "Dobroszyce", "Dziadowa Kłoda", "Międzybórz", "Oleśnica", "Syców", "Twardogóra"],
    oławski: ["Domaniów", "Jelcz-Laskowice", "Oława"],
    polkowicki: ["Chocianów", "Gaworzyce", "Grębocice", "Polkowice", "Przemków", "Radwanice"],
    strzeliński: ["Kondratowice", "Przeworno", "Strzelin", "Wiązów"],
    średzki: ["Kostomłoty", "Malczyce", "Miękinia", "Środa Śląska", "Udanin"],
    świdnicki: ["Dobromierz", "Jaworzyna Śląska", "Marcinowice", "Strzegom", "Świdnica", "Świebodzice"],
    trzebnicki: ["Oborniki Śląskie", "Prusice", "Trzebnica", "Wisznia Mała", "Zawonia", "Żmigród"],
    wałbrzyski: ["Czarny Bór", "Głuszyca", "Mieroszów", "Stare Bogaczowice", "Szczawno-Zdrój", "Walim"],
    wołowski: ["Brzeg Dolny", "Wińsko", "Wołów"],
    wrocławski: ["Czernica", "Długołęka", "Jordanów Śląski", "Kąty Wrocławskie", "Kobierzyce", "Mietków", "Siechnice", "Sobótka", "Żórawina"],
    ząbkowicki: ["Bardo", "Ciepłowody", "Kamieniec Ząbkowicki", "Stoszowice", "Ząbkowice Śląskie", "Ziębice", "Złoty Stok"],
    złotoryjski: ["Pielgrzymka", "Świerzawa", "Wojcieszów", "Zagrodno", "Złotoryja"],
    "Jelenia Góra": ["Jelenia Góra"],
    Legnica: ["Legnica"],
    Wałbrzych: ["Wałbrzych"],
    Wrocław: ["Wrocław"],
  },
  "kujawsko-pomorskie": {
    aleksandrowski: ["Aleksandrów Kujawski", "Bądkowo", "Ciechocinek", "Koneck", "Nieszawa", "Raciążek", "Waganiec", "Zakrzewo"],
    brodnicki: ["Bobrowo", "Brodnica", "Brzozie", "Górzno", "Jabłonowo Pomorskie", "Osiek", "Świedziebnia", "Zbiczno"],
    bydgoski: ["Białe Błota", "Dąbrowa Chełmińska", "Dobrcz", "Koronowo", "Nowa Wieś Wielka", "Osielsko", "Sicienko", "Solec Kujawski"],
    chełmiński: ["Chełmno", "Lisewo", "Papowo Biskupie", "Stolno", "Unisław"],
    "golubsko-dobrzyński": ["Ciechocin", "Golub-Dobrzyń", "Kowalewo Pomorskie", "Radomin", "Zbójno"],
    grudziądzki: ["Grudziądz", "Łasin", "Rogóźno", "Świecie nad Osą"],
    inowrocławski: ["Dąbrowa Biskupia", "Gniewkowo", "Inowrocław", "Janikowo", "Kruszwica", "Pakość", "Rojewo", "Złotniki Kujawskie"],
    lipnowski: ["Bobrowniki", "Chrostkowo", "Dobrzyń nad Wisłą", "Kikół", "Lipno", "Skępe", "Tłuchowo", "Wielgie"],
    mogileński: ["Dąbrowa", "Jeziora Wielkie", "Mogilno", "Strzelno"],
    nakielski: ["Kcynia", "Mrocza", "Nakło nad Notecią", "Sadki", "Szubin"],
    radziejowski: ["Bytoń", "Dobre", "Osięciny", "Piotrków Kujawski", "Radziejów", "Topólka"],
    rypiński: ["Brzuze", "Rogowo", "Rypin", "Skrwilno", "Wąpielsk"],
    sępoleński: ["Kamień Krajeński", "Sępólno Krajeńskie", "Sośno", "Więcbork"],
    świecki: ["Bukowiec", "Dragacz", "Drzycim", "Jeżewo", "Lniano", "Nowe", "Osie", "Pruszcz", "Świecie", "Świekatowo", "Warlubie"],
    toruński: ["Chełmża", "Czernikowo", "Lubicz", "Łubianka", "Obrowo", "Wielka Nieszawka", "Zławieś Wielka"],
    tucholski: ["Cekcyn", "Gostycyn", "Kęsowo", "Lubiewo", "Śliwice", "Tuchola"],
    wąbrzeski: ["Dębowa Łąka", "Książki", "Płużnica", "Ryńsk", "Wąbrzeźno"],
    włocławski: ["Baruchowo", "Boniewo", "Brześć Kujawski", "Chodecz", "Fabianki", "Izbica Kujawska", "Kowal", "Lubanie", "Lubraniec", "Włocławek"],
    żniński: ["Barcin", "Gąsawa", "Janowiec Wielkopolski", "Łabiszyn", "Żnin"],
    Bydgoszcz: ["Bydgoszcz"],
    Grudziądz: ["Grudziądz"],
    Toruń: ["Toruń"],
    Włocławek: ["Włocławek"],
  },
  lubelskie: {
    bialski: ["Biała Podlaska", "Drelów", "Janów Podlaski", "Konstantynów", "Leśna Podlaska", "Łomazy", "Międzyrzec Podlaski", "Piszczac", "Rokitno", "Rossosz", "Sławatycze", "Sosnówka", "Terespol", "Tuczna", "Wisznice", "Zalesie"],
    biłgorajski: ["Aleksandrów", "Biłgoraj", "Frampol", "Goraj", "Józefów", "Księżpol", "Łukowa", "Obsza", "Potok Górny", "Tarnogród", "Tereszpol", "Turobin"],
    chełmski: ["Białopole", "Dorohusk", "Dubienka", "Kamień", "Leśniowice", "Ruda-Huta", "Sawin", "Siedliszcze", "Wojsławice", "Wola Uhruska", "Żmudź"],
    hrubieszowski: ["Dołhobyczów", "Horodło", "Hrubieszów", "Mircze", "Trzeszczany", "Uchanie", "Werbkowice"],
    janowski: ["Annopol", "Batorz", "Chrzanów", "Dzwola", "Godziszów", "Janów Lubelski", "Modliborzyce", "Potok Wielki"],
    krasnostawski: ["Fajsławice", "Gorzków", "Izbica", "Krasnystaw", "Kraśniczyn", "Rudnik", "Siennica Różana", "Żółkiewka"],
    kraśnicki: ["Annopol", "Dzierzkowice", "Gościeradów", "Kraśnik", "Szastarka", "Trzydnik Duży", "Urzędów", "Wilkołaz", "Zakrzówek"],
    lubartowski: ["Abramów", "Firlej", "Jeziorzany", "Kamionka", "Kock", "Lubartów", "Michów", "Niemce", "Ostrów Lubelski", "Ostrówek", "Serniki", "Uścimów"],
    lubelski: ["Bełżyce", "Borzechów", "Bychawa", "Garbów", "Głusk", "Jabłonna", "Jastków", "Konopnica", "Krzczonów", "Ludwin", "Łęczna", "Mełgiew", "Niemce", "Niedrzwica Duża", "Piaski", "Spiczyn", "Strzyżewice", "Wojciechów", "Wólka"],
    łęczyński: ["Cyców", "Łęczna", "Ludwin", "Milejów", "Puchaczów", "Spiczyn"],
    łukowski: ["Adamów", "Krzywda", "Łuków", "Serokomla", "Stanin", "Stoczek Łukowski", "Trzebieszów", "Wojcieszków", "Wola Mysłowska"],
    opolski: ["Chodel", "Józefów nad Wisłą", "Karczmiska", "Łaziska", "Opole Lubelskie", "Poniatowa", "Wilków"],
    parczewski: ["Dębowa Kłoda", "Jabłoń", "Milanów", "Parczew", "Siemień", "Sosnowica"],
    puławski: ["Baranów", "Janowiec", "Kazimierz Dolny", "Końskowola", "Kurów", "Markuszów", "Nałęczów", "Puławy", "Wąwolnica", "Żyrzyn"],
    radzyński: ["Borki", "Czemierniki", "Kąkolewnica", "Komarówka Podlaska", "Radzyń Podlaski", "Ulan-Majorat", "Wohyń"],
    rycki: ["Dęblin", "Kłoczew", "Nowodwór", "Ryki", "Stężyca", "Ułęż"],
    świdnicki: ["Piaski", "Rybczewice", "Trawniki", "Świdnik"],
    tomaszowski: ["Bełżec", "Jarczów", "Józefów", "Krynice", "Łaszczów", "Rachanie", "Susiec", "Telatyn", "Tomaszów Lubelski", "Tyszowce", "Ulhówek"],
    włodawski: ["Hanna", "Hańsk", "Stary Brus", "Urszulin", "Włodawa", "Wola Uhruska", "Wyryki"],
    zamojski: ["Grabowiec", "Komarów-Osada", "Krasnobród", "Łabunie", "Miączyn", "Nielisz", "Radecznica", "Sitno", "Skierbieszów", "Stary Zamość", "Sułów", "Szczebrzeszyn", "Zamość", "Zwierzyniec"],
    "Biała Podlaska": ["Biała Podlaska"],
    Chełm: ["Chełm"],
    Lublin: ["Lublin"],
    Zamość: ["Zamość"],
  },
  lubuskie: {
    gorzowski: ["Deszczno", "Kłodawa", "Kostrzyn nad Odrą", "Lubiszyn", "Santok", "Witnica"],
    krośnieński: ["Bobrowice", "Bytnica", "Dąbie", "Gubin", "Krosno Odrzańskie", "Maszewo"],
    międzyrzecki: ["Bledzew", "Międzyrzecz", "Przytoczna", "Pszczew", "Skwierzyna", "Trzciel"],
    nowosolski: ["Bytom Odrzański", "Kolsko", "Kożuchów", "Nowa Sól", "Nowe Miasteczko", "Otyń", "Siedlisko"],
    słubicki: ["Cybinka", "Górzyca", "Ośno Lubuskie", "Rzepin", "Słubice"],
    "strzelecko-drezdenecki": ["Dobiegniew", "Drezdenko", "Stare Kurowo", "Strzelce Krajeńskie", "Zwierzyn"],
    sulęciński: ["Krzeszyce", "Lubniewice", "Słońsk", "Sulęcin", "Torzym"],
    świebodziński: ["Łagów", "Skąpe", "Szczaniec", "Świebodzin", "Zbąszynek"],
    wschowski: ["Szlichtyngowa", "Wschowa"],
    zielonogórski: ["Babimost", "Bojadła", "Czerwieńsk", "Kargowa", "Nowogród Bobrzański", "Sulechów", "Świdnica", "Trzebiechów", "Zabór"],
    żagański: ["Brzeźnica", "Gozdnica", "Iłowa", "Małomice", "Niegosławice", "Szprotawa", "Wymiarki", "Żagań"],
    żarski: ["Brody", "Jasień", "Lipinki Łużyckie", "Lubsko", "Łęknica", "Przewóz", "Trzebiel", "Tuplice", "Żary"],
    "Gorzów Wielkopolski": ["Gorzów Wielkopolski"],
    "Zielona Góra": ["Zielona Góra"],
  },
  lodzkie: {
    bełchatowski: ["Bełchatów", "Drużbice", "Kluki", "Kleszczów", "Rusiec", "Szczerców", "Zelów"],
    brzeziński: ["Brzeziny", "Dmosin", "Jeżów", "Rogów"],
    kutnowski: ["Bedlno", "Dąbrowice", "Góra Świętej Małgorzaty", "Krośniewice", "Kutno", "Łanięta", "Nowe Ostrowy", "Oporów", "Strzelce", "Żychlin"],
    łaski: ["Buczek", "Łask", "Sędziejowice", "Widawa", "Wodzierady"],
    łęczycki: ["Góra Świętej Małgorzaty", "Grabów", "Łęczyca", "Piątek", "Witonia"],
    łowicki: ["Bielawy", "Chąśno", "Domaniewice", "Kiernozia", "Kocierzew Południowy", "Łowicz", "Nieborów", "Zduny"],
    "łódź-wschodni": ["Andrespol", "Brójce", "Koluszki", "Nowosolna", "Rzgów", "Tuszyn"],
    opoczyński: ["Drzewica", "Mniszków", "Opoczno", "Paradyż", "Poświętne", "Sławno", "Żarnów"],
    pabianicki: ["Dobroń", "Ksawerów", "Lutomiersk", "Pabianice", "Parzęczew"],
    pajęczański: ["Działoszyn", "Kiełczygłów", "Nowa Brzeźnica", "Pajęczno", "Rząśnia", "Siemkowice", "Strzelce Wielkie", "Sulmierzyce"],
    piotrkowski: ["Aleksandrów", "Czarnocin", "Gorzkowice", "Grabica", "Łęki Szlacheckie", "Moszczenica", "Ręczno", "Rozprza", "Sulejów", "Wola Krzysztoporska", "Wolbórz"],
    poddębicki: ["Dalików", "Pęczniew", "Poddębice", "Uniejów", "Wartkowice", "Zadzim"],
    radomszczański: ["Dobryszyce", "Gomunice", "Kamieńsk", "Kobiele Wielkie", "Kodrąb", "Lgota Wielka", "Ładzice", "Masłowice", "Przedbórz", "Radomsko", "Wielgomłyny", "Żytno"],
    rawski: ["Biała Rawska", "Cielądz", "Rawa Mazowiecka", "Regnów", "Sadkowice"],
    sieradzki: ["Brzeźnio", "Burzenin", "Goszczanów", "Klonowa", "Sieradz", "Warta", "Wróblew", "Złoczew"],
    skierniewicki: ["Bolimów", "Głuchów", "Głowno", "Kowiesy", "Lipce Reymontowskie", "Maków", "Nowy Kawęczyn", "Skierniewice", "Słupia"],
    tomaszowski: ["Będków", "Budziszewice", "Czerniewice", "Inowłódź", "Lubochnia", "Rokiciny", "Rzeczyca", "Tomaszów Mazowiecki", "Ujazd", "Żelechlinek"],
    wieluński: ["Biała", "Czarnożyły", "Konopnica", "Mokrsko", "Ostrówek", "Pątnów", "Skomlin", "Wieluń", "Wierzchlas"],
    wieruszowski: ["Bolesławiec", "Czastary", "Galewice", "Lututów", "Łubnice", "Sokolniki", "Wieruszów"],
    zduńskowolski: ["Szadek", "Zapolice", "Zduńska Wola"],
    zgierski: ["Aleksandrów Łódzki", "Głowno", "Ozorków", "Parzęczew", "Stryków", "Zgierz"],
    Łódź: ["Łódź"],
    "Piotrków Trybunalski": ["Piotrków Trybunalski"],
    Skierniewice: ["Skierniewice"],
  },
  malopolskie: {
    bocheński: ["Bochnia", "Drwinia", "Lipnica Murowana", "Łapanów", "Nowy Wiśnicz", "Rzezawa", "Trzciana", "Żegocina"],
    brzeski: ["Borzęcin", "Brzesko", "Czchów", "Dębno", "Gnojnik", "Iwkowa", "Szczurowa"],
    chrzanowski: ["Alwernia", "Babice", "Chrzanów", "Libiąż", "Trzebinia"],
    dąbrowski: ["Dąbrowa Tarnowska", "Gręboszów", "Mędrzechów", "Olesno", "Radgoszcz", "Szczucin"],
    gorlicki: ["Biecz", "Bobowa", "Gorlice", "Lipinki", "Łużna", "Moszczenica", "Ropa", "Sękowa", "Uście Gorlickie"],
    krakowski: ["Czernichów", "Igołomia-Wawrzeńczyce", "Iwanowice", "Jerzmanowice-Przeginia", "Kocmyrzów-Luborzyca", "Liszki", "Michałowice", "Mogilany", "Niepołomice", "Skała", "Skawina", "Słomniki", "Sułoszowa", "Świątniki Górne", "Wielka Wieś", "Zabierzów", "Zielonki"],
    limanowski: ["Dobra", "Jodłownik", "Kamienica", "Laskowa", "Limanowa", "Mszana Dolna", "Niedźwiedź", "Słopnice", "Tymbark"],
    miechowski: ["Charsznica", "Gołcza", "Kozłów", "Książ Wielki", "Miechów", "Racławice", "Słaboszów"],
    myślenicki: ["Dobczyce", "Lubień", "Myślenice", "Pcim", "Raciechowice", "Siepraw", "Sułkowice", "Tokarnia", "Wiśniowa"],
    nowosądecki: ["Chełmiec", "Gródek nad Dunajcem", "Grybów", "Kamionka Wielka", "Korzenna", "Łącko", "Łososina Dolna", "Nawojowa", "Piwniczna-Zdrój", "Podegrodzie", "Rytro", "Stary Sącz"],
    nowotarski: ["Czarny Dunajec", "Jabłonka", "Krościenko nad Dunajcem", "Lipnica Wielka", "Łapsze Niżne", "Nowy Targ", "Ochotnica Dolna", "Raba Wyżna", "Rabka-Zdrój", "Spytkowice", "Szaflary"],
    olkuski: ["Bolesław", "Bukowno", "Klucze", "Olkusz", "Trzyciąż"],
    oświęcimski: ["Brzeszcze", "Chełmek", "Kęty", "Oświęcim", "Polanka Wielka", "Przeciszów", "Zator"],
    proszowicki: ["Koniusza", "Koszyce", "Nowe Brzesko", "Proszowice", "Radziemice"],
    suski: ["Budzów", "Bystra-Sidzina", "Jordanów", "Maków Podhalański", "Stryszawa", "Sucha Beskidzka", "Zawoja", "Zembrzyce"],
    tarnowski: ["Ciężkowice", "Lisia Góra", "Pleśna", "Radłów", "Ryglice", "Rzepiennik Strzyżewski", "Skrzyszów", "Szerzyny", "Tarnów", "Tuchów", "Wietrzychowice", "Wojnicz", "Zakliczyn"],
    tatrzański: ["Biały Dunajec", "Bukowina Tatrzańska", "Kościelisko", "Poronin", "Zakopane"],
    wadowicki: ["Andrychów", "Brzeźnica", "Kalwaria Zebrzydowska", "Lanckorona", "Mucharz", "Spytkowice", "Stryszów", "Tomice", "Wadowice", "Wieprz"],
    wielicki: ["Biskupice", "Gdów", "Kłaj", "Niepołomice", "Wieliczka"],
    Kraków: ["Kraków"],
    "Nowy Sącz": ["Nowy Sącz"],
    Tarnów: ["Tarnów"],
  },
  mazowieckie: {
    białobrzeski: ["Białobrzegi", "Promna", "Radzanów", "Stara Błotnica", "Stromiec", "Wyśmierzyce"],
    ciechanowski: ["Ciechanów", "Glinojeck", "Gołymin-Ośrodek", "Ojrzeń", "Opinogóra Górna", "Sońsk"],
    garwoliński: ["Garwolin", "Górzno", "Łaskarzew", "Maciejowice", "Miastków Kościelny", "Parysów", "Pilawa", "Sobolew", "Trojanów", "Wilga", "Żelechów"],
    gostyniński: ["Gostynin", "Łąck", "Pacyna", "Sanniki", "Szczawin Kościelny"],
    grodziski: ["Baranów", "Grodzisk Mazowiecki", "Jaktorów", "Milanówek", "Podkowa Leśna"],
    grójecki: ["Belsk Duży", "Błędów", "Chynów", "Goszczyn", "Grójec", "Jasieniec", "Mogielnica", "Nowe Miasto nad Pilicą", "Pniewy", "Warka"],
    kozienicki: ["Gniewoszów", "Głowaczów", "Grabów nad Pilicą", "Kozienice", "Magnuszew", "Sieciechów"],
    legionowski: ["Jabłonna", "Legionowo", "Nieporęt", "Serock", "Wieliszew"],
    lipski: ["Ciepielów", "Chotcza", "Lipsko", "Rzeczniów", "Sienno", "Solec nad Wisłą"],
    łosicki: ["Huszlew", "Łosice", "Olszanka", "Platerów", "Sarnaki", "Stara Kornica"],
    makowski: ["Czerwonka", "Krasnosielc", "Maków Mazowiecki", "Płoniawy-Bramura", "Rzewnie", "Szelków"],
    miński: ["Cegłów", "Dębe Wielkie", "Dobre", "Halinów", "Jakubów", "Kałuszyn", "Latowicz", "Mińsk Mazowiecki", "Mrozy", "Siennica", "Stanisławów"],
    mławski: ["Dzierzgowo", "Lipowiec Kościelny", "Mława", "Radzanów", "Strzegowo", "Stupsk", "Szreńsk", "Szydłowo", "Wiśniewo"],
    nowodworski: ["Czosnów", "Leoncin", "Nasielsk", "Nowy Dwór Mazowiecki", "Pomiechówek", "Zakroczym"],
    ostrołęcki: ["Baranowo", "Czarnia", "Czerwin", "Goworowo", "Kadzidło", "Lelis", "Łyse", "Myszyniec", "Olszewo-Borki", "Rzekuń", "Troszyn"],
    ostrowski: ["Andrzejewo", "Boguty-Pianki", "Brok", "Małkinia Górna", "Nur", "Ostrów Mazowiecka", "Stary Lubotyń", "Szulborze Wielkie", "Wąsewo", "Zaręby Kościelne"],
    otwocki: ["Celestynów", "Józefów", "Karczew", "Kołbiel", "Osieck", "Otwock", "Sobienie-Jeziory", "Wiązowna"],
    piaseczyński: ["Góra Kalwaria", "Konstancin-Jeziorna", "Lesznowola", "Piaseczno", "Prażmów", "Tarczyn"],
    płocki: ["Bielsk", "Bodzanów", "Brudzeń Duży", "Bulkowo", "Drobin", "Gąbin", "Mała Wieś", "Nowy Duninów", "Radzanowo", "Słupno", "Staroźreby", "Wyszogród"],
    płoński: ["Baboszewo", "Czerwińsk nad Wisłą", "Dzierzążnia", "Joniec", "Naruszewo", "Nowe Miasto nad Wisłą", "Płońsk", "Raciąż", "Sochocin", "Załuski"],
    pruszkowski: ["Brwinów", "Michałowice", "Nadarzyn", "Piastów", "Pruszków", "Raszyn"],
    przasnyski: ["Chorzele", "Jednorożec", "Krasne", "Krzynowłoga Mała", "Przasnysz", "Rozogi"],
    przysuski: ["Borkowice", "Gielniów", "Klwów", "Odrzywół", "Potworów", "Przysucha", "Rusinów", "Wieniawa"],
    pułtuski: ["Długosiodło", "Obryte", "Pokrzywnica", "Pułtusk", "Świercze", "Winnica", "Zatory"],
    radomski: ["Gózd", "Iłża", "Jastrzębia", "Jedlińsk", "Jedlnia-Letnisko", "Kowala", "Pionki", "Przytyk", "Skaryszew", "Wierzbica", "Wolanów", "Zakrzew"],
    siedlecki: ["Domanice", "Korczew", "Kotuń", "Mokobody", "Mordy", "Paprotnia", "Przesmyki", "Siedlce", "Skórzec", "Suchożebry", "Wiśniew", "Wodynie", "Zbuczyn"],
    sierpecki: ["Gozdowo", "Mochowo", "Rościszewo", "Sierpc", "Szczutowo", "Zawidz"],
    sochaczewski: ["Brochów", "Iłów", "Młodzieszyn", "Nowa Sucha", "Rybno", "Sochaczew", "Teresin"],
    sokołowski: ["Bielany", "Ceranów", "Jabłonna Lacka", "Kosów Lacki", "Sabnie", "Sokołów Podlaski", "Sterdyń"],
    szydłowiecki: ["Chlewiska", "Jastrząb", "Mirów", "Orońsko", "Szydłowiec"],
    "warszawski zachodni": ["Błonie", "Kampinos", "Leszno", "Łomianki", "Ożarów Mazowiecki", "Stare Babice"],
    węgrowski: ["Grębków", "Korytnica", "Liw", "Łochów", "Miedzna", "Sadowne", "Stoczek", "Węgrów", "Wierzbno"],
    wołomiński: ["Dąbrówka", "Jadów", "Klembów", "Kobyłka", "Marki", "Radzymin", "Strachówka", "Tłuszcz", "Wołomin", "Ząbki", "Zielonka"],
    wyszkowski: ["Brańszczyk", "Długosiodło", "Rząśnik", "Somianka", "Wyszków", "Zabrodzie"],
    zwoleński: ["Kazanów", "Policzna", "Przyłęk", "Tczów", "Zwoleń"],
    żuromiński: ["Bieżuń", "Kuczbork-Osada", "Lubowidz", "Lutocin", "Siemiątkowo", "Żuromin"],
    żyrardowski: ["Mszczonów", "Puszcza Mariańska", "Radziejowice", "Wiskitki", "Żyrardów"],
    Ostrołęka: ["Ostrołęka"],
    Płock: ["Płock"],
    Radom: ["Radom"],
    Siedlce: ["Siedlce"],
    Warszawa: ["Warszawa"],
  },
  opolskie: {
    brzeski: ["Brzeg", "Grodków", "Lewin Brzeski", "Lubsza", "Olszanka", "Skarbimierz"],
    głubczycki: ["Baborów", "Branice", "Głubczyce", "Kietrz"],
    "kędzierzyńsko-kozielski": ["Bierawa", "Cisek", "Kędzierzyn-Koźle", "Pawłowiczki", "Polska Cerekiew", "Reńska Wieś"],
    kluczborski: ["Byczyna", "Kluczbork", "Lasowice Wielkie", "Wołczyn"],
    krapkowicki: ["Gogolin", "Krapkowice", "Strzeleczki", "Walce", "Zdzieszowice"],
    namysłowski: ["Domaszowice", "Namysłów", "Pokój", "Świerczów", "Wilków"],
    nyski: ["Głuchołazy", "Kamiennik", "Korfantów", "Łambinowice", "Nysa", "Otmuchów", "Paczków", "Pakosławice", "Skoroszyce"],
    oleski: ["Dobrodzień", "Gorzów Śląski", "Kolonowskie", "Olesno", "Praszka", "Radłów", "Zębowice"],
    opolski: ["Chrząstowice", "Dąbrowa", "Dobrzeń Wielki", "Komprachcice", "Łubniany", "Murów", "Niemodlin", "Ozimek", "Popielów", "Prószków", "Tarnów Opolski", "Tułowice", "Turawa"],
    prudnicki: ["Biała", "Lubrza", "Prudnik"],
    strzelecki: ["Izbicko", "Jemielnica", "Leśnica", "Strzelce Opolskie", "Ujazd", "Zawadzkie"],
    Opole: ["Opole"],
  },
  podkarpackie: {
    bieszczadzki: ["Lesko", "Lutowiska", "Ustrzyki Dolne"],
    brzozowski: ["Brzozów", "Domaradz", "Dydnia", "Haczów", "Jasienica Rosielna", "Nozdrzec"],
    dębicki: ["Brzostek", "Czarna", "Dębica", "Jodłowa", "Pilzno", "Żyraków"],
    jarosławski: ["Chłopice", "Jarosław", "Laszki", "Pawłosiów", "Pruchnik", "Radymno", "Rokietnica", "Roźwienica", "Wiązownica"],
    jasielski: ["Brzyska", "Dębowiec", "Jasło", "Kołaczyce", "Krempna", "Nowy Żmigród", "Osiek Jasielski", "Skołyszyn", "Tarnowiec"],
    kolbuszowski: ["Cmolas", "Kolbuszowa", "Majdan Królewski", "Niwiska", "Raniżów", "Sokołów Małopolski"],
    krośnieński: ["Chorkówka", "Iwonicz-Zdrój", "Jedlicze", "Korczyna", "Krościenko Wyżne", "Miejsce Piastowe", "Rymanów", "Wojaszówka"],
    leski: ["Baligród", "Cisna", "Lesko", "Olszanica", "Solina"],
    leżajski: ["Grodzisko Dolne", "Kuryłówka", "Leżajsk", "Nowa Sarzyna"],
    lubaczowski: ["Cieszanów", "Horyniec-Zdrój", "Lubaczów", "Narol", "Oleszyce", "Stary Dzików", "Wielkie Oczy"],
    łańcucki: ["Białobrzegi", "Czarna", "Łańcut", "Markowa", "Rakszawa", "Żołynia"],
    mielecki: ["Borowa", "Czermin", "Gawłuszowice", "Mielec", "Padew Narodowa", "Przecław", "Radomyśl Wielki", "Tuszów Narodowy", "Wadowice Górne"],
    niżański: ["Harasiuki", "Jarocin", "Jeżowe", "Nisko", "Rudnik nad Sanem", "Ulanów"],
    przemyski: ["Bircza", "Dubiecko", "Fredropol", "Krasiczyn", "Krzywcza", "Medyka", "Orły", "Stubno", "Żurawica"],
    przeworski: ["Adamówka", "Gać", "Jawornik Polski", "Kańczuga", "Przeworsk", "Sieniawa", "Tryńcza", "Zarzecze"],
    "ropczycko-sędziszowski": ["Iwierzyce", "Ostrów", "Ropczyce", "Sędziszów Małopolski", "Wielopole Skrzyńskie"],
    rzeszowski: ["Błażowa", "Boguchwała", "Chmielnik", "Głogów Małopolski", "Hyżne", "Krasne", "Lubenia", "Niebylec", "Świlcza", "Tyczyn"],
    sanocki: ["Besko", "Bukowsko", "Sanok", "Tyrawa Wołoska", "Zagórz", "Zarszyn"],
    stalowowolski: ["Bojanów", "Pysznica", "Radomyśl nad Sanem", "Stalowa Wola", "Zaklików", "Zaleszany"],
    strzyżowski: ["Frysztak", "Niebylec", "Strzyżów", "Wiśniowa"],
    tarnobrzeski: ["Baranów Sandomierski", "Gorzyce", "Grębów", "Nowa Dęba"],
    Krosno: ["Krosno"],
    Przemyśl: ["Przemyśl"],
    Rzeszów: ["Rzeszów"],
    Tarnobrzeg: ["Tarnobrzeg"],
  },
  podlaskie: {
    augustowski: ["Augustów", "Bargłów Kościelny", "Lipsk", "Nowinka", "Płaska", "Sztabin"],
    białostocki: ["Choroszcz", "Czarna Białostocka", "Dobrzyniewo Duże", "Gródek", "Juchnowiec Kościelny", "Łapy", "Michałowo", "Poświętne", "Supraśl", "Turośń Kościelna", "Wasilków", "Zabłudów"],
    bielski: ["Bielsk Podlaski", "Boćki", "Brańsk", "Orla", "Rudka", "Wyszki"],
    grajewski: ["Grajewo", "Rajgród", "Radziłów", "Szczuczyn", "Wąsosz"],
    hajnowski: ["Białowieża", "Czeremcha", "Czyże", "Dubicze Cerkiewne", "Hajnówka", "Kleszczele", "Narew", "Narewka"],
    kolneński: ["Grabowo", "Kolno", "Mały Płock", "Stawiski", "Turośl"],
    łomżyński: ["Jedwabne", "Łomża", "Miastkowo", "Nowogród", "Piątnica", "Przytuły", "Śniadowo", "Wizna", "Zbójna"],
    moniecki: ["Goniądz", "Jasionówka", "Jaświły", "Knyszyn", "Krypno", "Mońki", "Trzcianne"],
    sejneński: ["Giby", "Krasnopol", "Puńsk", "Sejny"],
    siemiatycki: ["Drohiczyn", "Dziadkowice", "Grodzisk", "Mielnik", "Milejczyce", "Nurzec-Stacja", "Perlejewo", "Siemiatycze"],
    sokólski: ["Dąbrowa Białostocka", "Janów", "Korycin", "Krynki", "Kuźnica", "Nowy Dwór", "Sidra", "Sokółka", "Suchowola", "Szudziałowo"],
    suwalski: ["Bakałarzewo", "Filipów", "Jeleniewo", "Przerośl", "Raczki", "Rutka-Tartak", "Suwałki", "Szypliszki", "Wiżajny"],
    wysokomazowiecki: ["Ciechanowiec", "Czyżew", "Klukowo", "Kobylin-Borzymy", "Nowe Piekuty", "Sokoły", "Szepietowo", "Wysokie Mazowieckie"],
    zambrowski: ["Kołaki Kościelne", "Rutki", "Szumowo", "Zambrów", "Zawady"],
    Białystok: ["Białystok"],
    Łomża: ["Łomża"],
    Suwałki: ["Suwałki"],
  },
  pomorskie: {
    bytowski: ["Borzytuchom", "Bytów", "Czarna Dąbrówka", "Kołczygłowy", "Lipnica", "Miastko", "Parchowo", "Studzienice", "Trzebielino", "Tuchomie"],
    chojnicki: ["Brusy", "Chojnice", "Czersk", "Konarzyny"],
    człuchowski: ["Czarne", "Człuchów", "Debrzno", "Koczała", "Przechlewo", "Rzeczenica"],
    gdański: ["Cedry Wielkie", "Kolbudy", "Pruszcz Gdański", "Przywidz", "Pszczółki", "Suchy Dąb", "Trąbki Wielkie"],
    kartuski: ["Chmielno", "Kartuzy", "Przodkowo", "Sierakowice", "Somonino", "Stężyca", "Sulęczyno", "Żukowo"],
    kościerski: ["Dziemiany", "Karsin", "Kościerzyna", "Liniewo", "Lipusz", "Nowa Karczma", "Stara Kiszewa"],
    kwidzyński: ["Gardeja", "Kwidzyn", "Prabuty", "Ryjewo", "Sadlinki"],
    lęborski: ["Cewice", "Czarna Dąbrówka", "Lębork", "Nowa Wieś Lęborska", "Wicko"],
    malborski: ["Lichnowy", "Malbork", "Miłoradz", "Nowy Staw", "Stare Pole"],
    nowodworski: ["Nowy Dwór Gdański", "Ostaszewo", "Stegna", "Sztutowo"],
    pucki: ["Hel", "Jastarnia", "Kosakowo", "Krokowa", "Puck", "Władysławowo"],
    słupski: ["Damnica", "Dębnica Kaszubska", "Główczyce", "Kępice", "Kobylnica", "Potęgowo", "Słupsk", "Smołdzino"],
    starogardzki: ["Bobowo", "Czarna Woda", "Kaliska", "Lubichowo", "Osieczna", "Skarszewy", "Skórcz", "Smętowo Graniczne", "Starogard Gdański", "Zblewo"],
    sztumski: ["Dzierzgoń", "Mikołajki Pomorskie", "Stary Dzierzgoń", "Stary Targ", "Sztum"],
    tczewski: ["Gniew", "Morzeszczyn", "Pelplin", "Subkowy", "Tczew"],
    wejherowski: ["Gniewino", "Linia", "Luzino", "Łęczyce", "Reda", "Rumia", "Szemud", "Wejherowo"],
    Gdańsk: ["Gdańsk"],
    Gdynia: ["Gdynia"],
    Słupsk: ["Słupsk"],
    Sopot: ["Sopot"],
  },
  slaskie: {
    będziński: ["Będzin", "Bobrowniki", "Czeladź", "Mierzęcice", "Psary", "Siewierz", "Sławków", "Wojkowice"],
    bielski: ["Bestwina", "Buczkowice", "Czechowice-Dziedzice", "Jasienica", "Jaworze", "Kozy", "Porąbka", "Szczyrk", "Wilkowice"],
    cieszyński: ["Brenna", "Chybie", "Dębowiec", "Goleszów", "Hażlach", "Istebna", "Skoczów", "Strumień", "Ustroń", "Wisła", "Zebrzydowice"],
    częstochowski: ["Blachownia", "Dąbrowa Zielona", "Janów", "Kamienica Polska", "Kłomnice", "Konopiska", "Kruszyna", "Lelów", "Mstów", "Mykanów", "Olsztyn", "Poczesna", "Przyrów", "Rędziny", "Starcza"],
    gliwicki: ["Gierałtowice", "Knurów", "Pilchowice", "Rudziniec", "Sośnicowice", "Toszek", "Wielowieś"],
    kłobucki: ["Kłobuck", "Lipie", "Miedźno", "Opatów", "Panki", "Popów", "Przystajń", "Wręczyca Wielka"],
    lubliniecki: ["Boronów", "Ciasna", "Herby", "Kochanowice", "Koszęcin", "Lubliniec", "Pawonków", "Woźniki"],
    mikołowski: ["Łaziska Górne", "Mikołów", "Orzesze", "Ornontowice", "Wyry"],
    myszkowski: ["Koziegłowy", "Myszków", "Niegowa", "Poraj"],
    pszczyński: ["Goczałkowice-Zdrój", "Kobiór", "Miedźna", "Pawłowice", "Pszczyna", "Suszec"],
    raciborski: ["Kornowac", "Krzanowice", "Krzyżanowice", "Kuźnia Raciborska", "Nędza", "Pietrowice Wielkie", "Racibórz"],
    rybnicki: ["Czerwionka-Leszczyny", "Gaszowice", "Jejkowice", "Lyski", "Świerklany"],
    tarnogórski: ["Kalety", "Krupski Młyn", "Miasteczko Śląskie", "Ożarowice", "Świerklaniec", "Tarnowskie Góry", "Tworóg", "Zbrosławice"],
    wodzisławski: ["Godów", "Gorzyce", "Lubomia", "Marklowice", "Mszana", "Pszów", "Radlin", "Rydułtowy", "Wodzisław Śląski"],
    zawierciański: ["Irządze", "Kroczyce", "Łazy", "Ogrodzieniec", "Pilica", "Poręba", "Szczekociny", "Włodowice", "Zawiercie", "Żarnowiec"],
    żywiecki: ["Czernichów", "Gilowice", "Jeleśnia", "Koszarawa", "Lipowa", "Łodygowice", "Milówka", "Radziechowy-Wieprz", "Rajcza", "Ślemień", "Świnna", "Ujsoły", "Węgierska Górka", "Żywiec"],
    "Bielsko-Biała": ["Bielsko-Biała"],
    Bytom: ["Bytom"],
    Chorzów: ["Chorzów"],
    Częstochowa: ["Częstochowa"],
    "Dąbrowa Górnicza": ["Dąbrowa Górnicza"],
    Gliwice: ["Gliwice"],
    "Jastrzębie-Zdrój": ["Jastrzębie-Zdrój"],
    Jaworzno: ["Jaworzno"],
    Katowice: ["Katowice"],
    Mysłowice: ["Mysłowice"],
    "Piekary Śląskie": ["Piekary Śląskie"],
    "Ruda Śląska": ["Ruda Śląska"],
    Rybnik: ["Rybnik"],
    "Siemianowice Śląskie": ["Siemianowice Śląskie"],
    Sosnowiec: ["Sosnowiec"],
    Świętochłowice: ["Świętochłowice"],
    Tychy: ["Tychy"],
    Zabrze: ["Zabrze"],
    Żory: ["Żory"],
  },
  swietokrzyskie: {
    buski: ["Busko-Zdrój", "Gnojno", "Nowy Korczyn", "Pacanów", "Solec-Zdrój", "Stopnica", "Tuczępy", "Wiślica"],
    jędrzejowski: ["Imielno", "Jędrzejów", "Małogoszcz", "Nagłowice", "Oksa", "Sędziszów", "Słupia", "Sobków", "Wodzisław"],
    kazimierski: ["Bejsce", "Czarnocin", "Kazimierza Wielka", "Opatowiec", "Skalbmierz"],
    kielecki: ["Bieliny", "Bodzentyn", "Chęciny", "Chmielnik", "Daleszyce", "Górno", "Łagów", "Łopuszno", "Masłów", "Miedziana Góra", "Mniów", "Morawica", "Nowa Słupia", "Raków", "Sitkówka-Nowiny", "Strawczyn", "Zagnańsk"],
    konecki: ["Fałków", "Gowarczów", "Końskie", "Radoszyce", "Ruda Maleniecka", "Smyków", "Stąporków"],
    opatowski: ["Baćkowice", "Iwaniska", "Lipnik", "Opatów", "Ożarów", "Sadowie", "Tarłów", "Wojciechowice"],
    ostrowiecki: ["Bałtów", "Bodzechów", "Ćmielów", "Kunów", "Ostrowiec Świętokrzyski", "Waśniów"],
    pińczowski: ["Działoszyce", "Kije", "Michałów", "Pińczów", "Złota"],
    sandomierski: ["Dwikozy", "Gorzyce", "Klimontów", "Koprzywnica", "Łoniów", "Obrazów", "Samborzec", "Sandomierz", "Wilczyce", "Zawichost"],
    skarżyski: ["Bliżyn", "Łączna", "Skarżysko-Kamienna", "Suchedniów"],
    starachowicki: ["Brody", "Mirzec", "Pawłów", "Starachowice", "Wąchock"],
    staszowski: ["Bogoria", "Czajków", "Łubnice", "Oleśnica", "Osiek", "Połaniec", "Rytwiany", "Staszów", "Szydłów", "Tuczępy"],
    włoszczowski: ["Kluczewsko", "Krasocin", "Moskorzew", "Secemin", "Włoszczowa"],
    Kielce: ["Kielce"],
  },
  "warminsko-mazurskie": {
    bartoszycki: ["Bartoszyce", "Bisztynek", "Górowo Iławeckie", "Sępopol"],
    braniewski: ["Braniewo", "Frombork", "Lelkowo", "Pieniężno", "Płoskinia", "Wilczęta"],
    działdowski: ["Działdowo", "Iłowo-Osada", "Lidzbark", "Płośnica", "Rybno"],
    elbląski: ["Gronowo Elbląskie", "Markusy", "Milejewo", "Młynary", "Pasłęk", "Rychliki", "Tolkmicko"],
    ełcki: ["Ełk", "Kalinowo", "Prostki", "Stare Juchy"],
    giżycki: ["Giżycko", "Kruklanki", "Miłki", "Ryn", "Wydminy"],
    gołdapski: ["Banie Mazurskie", "Dubeninki", "Gołdap"],
    iławski: ["Iława", "Kisielice", "Lubawa", "Susz", "Zalewo"],
    kętrzyński: ["Barciany", "Kętrzyn", "Korsze", "Reszel", "Srokowo"],
    lidzbarski: ["Kiwity", "Lidzbark Warmiński", "Lubomino", "Orneta"],
    mrągowski: ["Mikołajki", "Mrągowo", "Piecki", "Sorkwity"],
    nidzicki: ["Janowiec Kościelny", "Janowo", "Kozłowo", "Nidzica"],
    nowomiejski: ["Biskupiec", "Grodziczno", "Kurzętnik", "Nowe Miasto Lubawskie"],
    olecki: ["Kowale Oleckie", "Olecko", "Świętajno", "Wieliczki"],
    olsztyński: ["Barczewo", "Biskupiec", "Dobre Miasto", "Dywity", "Gietrzwałd", "Jeziorany", "Jonkowo", "Kolno", "Purda", "Stawiguda", "Świątki"],
    ostródzki: ["Dąbrówno", "Grunwald", "Łukta", "Małdyty", "Miłakowo", "Miłomłyn", "Morąg", "Ostróda"],
    piski: ["Biała Piska", "Pisz", "Ruciane-Nida"],
    szczycieński: ["Dźwierzuty", "Jedwabno", "Pasym", "Rozogi", "Szczytno", "Świętajno", "Wielbark"],
    węgorzewski: ["Budry", "Pozezdrze", "Węgorzewo"],
    Elbląg: ["Elbląg"],
    Olsztyn: ["Olsztyn"],
  },
  wielkopolskie: {
    chodzieski: ["Chodzież", "Margonin", "Szamocin"],
    "czarnkowsko-trzcianecki": ["Czarnków", "Drawsko", "Krzyż Wielkopolski", "Lubasz", "Połajewo", "Trzcianka", "Wieleń"],
    gnieźnieński: ["Gniezno", "Kiszkowo", "Kłecko", "Łubowo", "Mieleszyn", "Niechanowo", "Trzemeszno", "Witkowo"],
    gostyński: ["Borek Wielkopolski", "Gostyń", "Krobia", "Pępowo", "Piaski", "Pogorzela", "Poniec"],
    grodziski: ["Granowo", "Grodzisk Wielkopolski", "Kamieniec", "Rakoniewice", "Wielichowo"],
    jarociński: ["Jaraczewo", "Jarocin", "Kotlin", "Żerków"],
    kaliski: ["Blizanów", "Brzeziny", "Ceków-Kolonia", "Godziesze Wielkie", "Koźminek", "Lisków", "Mycielin", "Opatówek", "Stawiszyn", "Szczytniki", "Żelazków"],
    kępiński: ["Baranów", "Bralin", "Kępno", "Łęka Opatowska", "Perzów", "Rychtal", "Trzcinica"],
    kolski: ["Babiak", "Dąbie", "Grzegorzew", "Kłodawa", "Koło", "Kościelec", "Olszówka", "Osiek Mały", "Przedecz"],
    koniński: ["Golina", "Grodziec", "Kazimierz Biskupi", "Kleczew", "Kramsk", "Krzymów", "Rychwał", "Rzgów", "Skulsk", "Sompolno", "Stare Miasto", "Ślesin", "Wierzbinek", "Wilczyn"],
    kościański: ["Czempiń", "Kościan", "Krzywiń", "Śmigiel"],
    krotoszyński: ["Koźmin Wielkopolski", "Krotoszyn", "Rozdrażew", "Sulmierzyce", "Zduny"],
    leszczyński: ["Krzemieniewo", "Lipno", "Osieczna", "Rydzyna", "Święciechowa", "Wijewo", "Włoszakowice"],
    międzychodzki: ["Chrzypsko Wielkie", "Kwilcz", "Międzychód", "Sieraków"],
    nowotomyski: ["Kuślin", "Lwówek", "Nowy Tomyśl", "Opalenica", "Zbąszyń"],
    obornicki: ["Oborniki", "Rogoźno", "Ryczywół"],
    ostrowski: ["Nowe Skalmierzyce", "Ostrów Wielkopolski", "Przygodzice", "Raszków", "Sieroszewice", "Sośnie"],
    ostrzeszowski: ["Czajków", "Doruchów", "Grabów nad Prosną", "Kobyla Góra", "Kraszewice", "Mikstat", "Ostrzeszów"],
    pilski: ["Białośliwie", "Kaczory", "Łobżenica", "Miasteczko Krajeńskie", "Piła", "Szydłowo", "Ujście", "Wysoka"],
    pleszewski: ["Chocz", "Czermin", "Dobrzyca", "Gołuchów", "Pleszew"],
    poznański: ["Buk", "Czerwonak", "Dopiewo", "Kleszczewo", "Komorniki", "Kostrzyn", "Kórnik", "Luboń", "Mosina", "Murowana Goślina", "Pobiedziska", "Rokietnica", "Stęszew", "Suchy Las", "Swarzędz", "Szamotuły"],
    rawicki: ["Bojanowo", "Jutrosin", "Pakosław", "Rawicz", "Miejska Górka"],
    słupecki: ["Lądek", "Orchowo", "Ostrowite", "Powidz", "Słupca", "Strzałkowo"],
    szamotulski: ["Duszniki", "Kaźmierz", "Obrzycko", "Ostroróg", "Pniewy", "Szamotuły", "Wronki"],
    średzki: ["Dominowo", "Krzykosy", "Nowe Miasto nad Wartą", "Środa Wielkopolska", "Zaniemyśl"],
    śremski: ["Brodnica", "Dolsk", "Książ Wielkopolski", "Śrem"],
    turecki: ["Brudzew", "Dobra", "Kawęczyn", "Malanów", "Przykona", "Tuliszków", "Turek", "Władysławów"],
    wągrowiecki: ["Damasławek", "Gołańcz", "Mieścisko", "Skoki", "Wągrowiec"],
    wolsztyński: ["Przemęt", "Siedlec", "Wolsztyn"],
    wrzesiński: ["Kołaczkowo", "Miłosław", "Nekla", "Pyzdry", "Września"],
    złotowski: ["Jastrowie", "Krajenka", "Lipka", "Okonek", "Tarnówka", "Zakrzewo", "Złotów"],
    Kalisz: ["Kalisz"],
    Konin: ["Konin"],
    Leszno: ["Leszno"],
    Poznań: ["Poznań"],
  },
  zachodniopomorskie: {
    białogardzki: ["Białogard", "Karlino", "Tychowo"],
    choszczeński: ["Bierzwnik", "Choszczno", "Drawno", "Krzęcin", "Pełczyce", "Recz"],
    drawski: ["Czaplinek", "Drawsko Pomorskie", "Kalisz Pomorski", "Ostrowice", "Wierzchowo", "Złocieniec"],
    goleniowski: ["Goleniów", "Maszewo", "Nowogard", "Osina", "Stepnica"],
    gryficki: ["Brojce", "Gryfice", "Karnice", "Płoty", "Rewal", "Trzebiatów"],
    gryfiński: ["Banie", "Cedynia", "Chojna", "Gryfino", "Mieszkowice", "Moryń", "Stare Czarnowo", "Trzcińsko-Zdrój", "Widuchowa"],
    kamieński: ["Dziwnów", "Golczewo", "Kamień Pomorski", "Międzyzdroje", "Świerzno", "Wolin"],
    kołobrzeski: ["Dygowo", "Gościno", "Kołobrzeg", "Rymań", "Siemyśl", "Ustronie Morskie"],
    koszaliński: ["Będzino", "Biesiekierz", "Bobolice", "Manowo", "Mielno", "Polanów", "Sianów", "Świeszyno"],
    łobeski: ["Dobra", "Łobez", "Radowo Małe", "Resko", "Węgorzyno"],
    myśliborski: ["Barlinek", "Dębno", "Myślibórz", "Nowogródek Pomorski"],
    policki: ["Dobra", "Kołbaskowo", "Nowe Warpno", "Police"],
    pyrzycki: ["Bielice", "Kozielice", "Lipiany", "Przelewice", "Pyrzyce", "Warnice"],
    sławieński: ["Darłowo", "Malechowo", "Postomino", "Sławno"],
    stargardzki: ["Chociwel", "Dolice", "Ińsko", "Kobylanka", "Marianowo", "Stargard", "Stara Dąbrowa", "Suchań"],
    szczecinecki: ["Barwice", "Biały Bór", "Borne Sulinowo", "Grzmiąca", "Szczecinek"],
    świdwiński: ["Brzeżno", "Połczyn-Zdrój", "Rąbino", "Sławoborze", "Świdwin"],
    walecki: ["Człopa", "Mirosławiec", "Tuczno", "Wałcz"],
    Koszalin: ["Koszalin"],
    Szczecin: ["Szczecin"],
    Świnoujście: ["Świnoujście"],
  },
};

export function getPowiats(voivodeship: string): string[] {
  const data = TERYT[voivodeship];
  if (!data) return [];
  return Object.keys(data).sort((a, b) => a.localeCompare(b, "pl"));
}

export function getGminas(voivodeship: string, powiat: string): string[] {
  const data = TERYT[voivodeship];
  if (!data) return [];
  return data[powiat] ?? [];
}
